#!/usr/bin/env tsx
/**
 * Runs effect-analyze on each progressive workflow step and outputs:
 *   1. RAILWAY-EVOLUTION.md  — markdown with mermaid blocks
 *   2. index.html            — styled presentation using Tailwind + Mermaid CDN
 *
 * Every diagram in both outputs is the raw, unedited mermaid from effect-analyze.
 *
 * Usage:
 *   cd demos/04-observability-effect
 *   npx tsx src/transfer/evolution/analyze.ts
 */
import { execSync } from "node:child_process"
import { writeFileSync } from "node:fs"
import { dirname, join, resolve } from "node:path"

const STEPS = [
  { file: "step-1-validate.ts", title: "Step 1: Validate input", desc: "One operation. One possible failure. The type system already knows what can go wrong." },
  { file: "step-2-fetch-rate.ts", title: "Step 2: + Fetch exchange rate", desc: "A second step, a second way to fail. The error channel grows automatically." },
  { file: "step-3-convert.ts", title: "Step 3: + Check balance & convert", desc: "Balance check introduces a new failure mode. The compiler tracks it — you don't have to." },
  { file: "step-4-execute.ts", title: "Step 4: + Execute transfer", desc: "The money moves. Two new failure modes from the external provider. Still zero runtime needed to see them." },
  { file: "step-5-confirm.ts", title: "Step 5: + Send confirmation (complete)", desc: "The complete workflow. Six effects, six error channels, zero ambiguity. Every path is visible before a single line runs." },
]

const scriptDir = dirname(new URL(import.meta.url).pathname)
const projectRoot = resolve(scriptDir, "../../..")

function analyze(file: string, format: string): string {
  const filePath = join(scriptDir, file)
  const cmd = `npx effect-analyze "${filePath}" --format ${format}`
  const output = execSync(cmd, { encoding: "utf-8", cwd: projectRoot })
  return output
    .split("\n")
    .filter((line) => !line.startsWith("Analyzing") && !line.startsWith("Found"))
    .join("\n")
    .trim()
}

// ---------------------------------------------------------------------------
// Collect analysis data
// ---------------------------------------------------------------------------

type StepData = {
  title: string
  desc: string
  railway: string
  explain: string
  stats: string
  errorPaths: string[]
  totalEffects: number
}

const results: StepData[] = []

for (const step of STEPS) {
  const railway = analyze(step.file, "mermaid-railway")
  const explain = analyze(step.file, "explain")
  const stats = analyze(step.file, "stats")

  // Extract error names from the explain output
  const errorMatch = explain.match(/Error paths: (.+)/)
  const errorPaths = errorMatch
    ? errorMatch[1].split(", ").map((e) => e.trim())
    : []

  // Extract totalEffects from stats JSON
  let totalEffects = 0
  try {
    const parsed = JSON.parse(stats)
    totalEffects = parsed[0]?.stats?.totalEffects ?? 0
  } catch {}

  results.push({ title: step.title, desc: step.desc, railway, explain, stats, errorPaths, totalEffects })

  console.log(`\n${"=".repeat(60)}`)
  console.log(step.title)
  console.log("=".repeat(60))
  console.log(railway)
}

// ---------------------------------------------------------------------------
// 1. Generate RAILWAY-EVOLUTION.md
// ---------------------------------------------------------------------------

const md: string[] = []
md.push("# Send Money Workflow: Railway Diagram Evolution\n")
md.push("Each step adds one more operation to the pipeline.")
md.push("The railway diagram shows the happy path (ok) and every error branch.\n")
md.push("Generated by `effect-analyze` — static analysis, no code executed.\n")

for (const r of results) {
  md.push(`## ${r.title}\n`)
  md.push("```mermaid")
  md.push(r.railway)
  md.push("```\n")
  md.push("<details><summary>Analysis</summary>\n")
  md.push("```")
  md.push(r.explain)
  md.push("```\n")
  md.push("```json")
  md.push(r.stats)
  md.push("```\n")
  md.push("</details>\n")
}

const mdPath = join(scriptDir, "RAILWAY-EVOLUTION.md")
writeFileSync(mdPath, md.join("\n") + "\n")
console.log(`\n\nWritten markdown to ${mdPath}`)

// Write raw per-step outputs
const rawDir = join(scriptDir, "raw")
const { mkdirSync, existsSync } = await import("node:fs")
if (!existsSync(rawDir)) mkdirSync(rawDir)

for (let i = 0; i < results.length; i++) {
  const r = results[i]
  const prefix = `step-${i + 1}`
  writeFileSync(join(rawDir, `${prefix}-railway.mmd`), r.railway + "\n")
  writeFileSync(join(rawDir, `${prefix}-explain.txt`), r.explain + "\n")
  writeFileSync(join(rawDir, `${prefix}-stats.json`), r.stats + "\n")
}
console.log(`Written raw analysis to ${rawDir}/`)

// ---------------------------------------------------------------------------
// 2. Generate index.html
// ---------------------------------------------------------------------------

function escapeHtml(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;")
}

function stepSection(r: StepData, index: number): string {
  const num = index + 1
  const delay = (index * 0.1 + 0.1).toFixed(1)
  const errTags = r.errorPaths
    .map(
      (e, i) =>
        `<span class="err-tag inline-flex items-center gap-1.5 px-2.5 py-1 rounded text-xs font-mono bg-err/8 text-err border border-err/15" style="animation-delay:${(i * 0.1).toFixed(1)}s">${escapeHtml(e)}</span>`
    )
    .join("\n          ")

  return `
    <!-- Step ${num} -->
    <section id="step-${num}" class="step-card mb-20 md:mb-28" style="animation-delay: ${delay}s">
      <div class="flex items-start gap-6 mb-8">
        <div class="flex-shrink-0 flex flex-col items-center">
          <div class="timeline-dot w-10 h-10 rounded-full bg-accent text-paper flex items-center justify-center font-display text-xl font-bold">${num}</div>
        </div>
        <div>
          <h2 class="font-display text-3xl md:text-4xl">${escapeHtml(r.title.replace(/^Step \d+: /, ""))}</h2>
          <p class="text-muted mt-2 max-w-lg">${escapeHtml(r.desc)}</p>
        </div>
      </div>
      <div class="ml-0 md:ml-16">
        <div class="bg-white border border-ink/8 rounded-lg p-6 md:p-10 shadow-sm">
          <div class="mermaid-wrap">
            <pre class="mermaid">
${r.railway}
            </pre>
          </div>
        </div>
        <div class="mt-4 flex flex-wrap gap-2">
          ${errTags}
        </div>
        <div class="mt-3 flex gap-6 text-xs font-mono text-muted">
          <span class="stat-num"><strong class="text-ink">${r.totalEffects}</strong> effect${r.totalEffects === 1 ? "" : "s"}</span>
          <span class="stat-num"><strong class="text-ink">${r.errorPaths.length}</strong> error path${r.errorPaths.length === 1 ? "" : "s"}</span>
        </div>
        <details class="mt-4">
          <summary class="text-xs font-mono text-muted cursor-pointer hover:text-ink transition-colors">raw effect-analyze output</summary>
          <pre class="mt-2 p-4 bg-ink text-paper/80 rounded-lg text-xs font-mono overflow-x-auto leading-relaxed">${escapeHtml(r.explain)}</pre>
        </details>
      </div>
    </section>`
}

const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Railway Evolution — Static Analysis of a Money Transfer Workflow</title>
  <script src="https://cdn.tailwindcss.com"><\/script>
  <script src="https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.min.js"><\/script>
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=DM+Mono:ital,wght@0,300;0,400;0,500;1,400&family=Instrument+Serif:ital@0;1&family=Satoshi:wght@400;500;700;900&display=swap" rel="stylesheet" />
  <script>
    tailwind.config = {
      theme: {
        extend: {
          fontFamily: {
            display: ['"Instrument Serif"', 'Georgia', 'serif'],
            body: ['Satoshi', 'system-ui', 'sans-serif'],
            mono: ['"DM Mono"', 'monospace'],
          },
          colors: {
            ink: '#0a0a0a',
            paper: '#f5f0e8',
            warm: '#e8dfd0',
            accent: '#c44d2b',
            ok: '#2d6a4f',
            err: '#9d0208',
            muted: '#6b6560',
          },
        },
      },
    }
  <\/script>
  <style>
    html { scroll-behavior: smooth; }
    body { background: #f5f0e8; }
    body::before {
      content: '';
      position: fixed;
      inset: 0;
      opacity: 0.03;
      pointer-events: none;
      z-index: 100;
      background-image: url("data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)'/%3E%3C/svg%3E");
      background-size: 256px 256px;
    }
    .step-card {
      opacity: 0;
      transform: translateY(32px);
      animation: rise 0.6s ease-out forwards;
    }
    @keyframes rise { to { opacity: 1; transform: translateY(0); } }
    .mermaid-wrap svg { max-width: 100%; height: auto; }
    .timeline-dot { animation: pulse 2s ease-in-out infinite; }
    @keyframes pulse {
      0%, 100% { box-shadow: 0 0 0 0 rgba(196,77,43,0.3); }
      50% { box-shadow: 0 0 0 8px rgba(196,77,43,0); }
    }
    .err-tag { animation: slideIn 0.4s ease-out both; }
    @keyframes slideIn {
      from { opacity: 0; transform: translateX(-8px); }
      to { opacity: 1; transform: translateX(0); }
    }
    .stat-num { font-variant-numeric: tabular-nums; }
    #progress { transform-origin: left; transform: scaleX(0); transition: transform 0.1s linear; }
  </style>
</head>
<body class="font-body text-ink min-h-screen relative">

  <!-- Scroll progress -->
  <div class="fixed top-0 left-0 right-0 h-[2px] z-50">
    <div id="progress" class="h-full bg-accent w-full"></div>
  </div>

  <!-- Header -->
  <header class="relative overflow-hidden border-b border-ink/10">
    <div class="max-w-6xl mx-auto px-6 pt-20 pb-16 md:pt-28 md:pb-20">
      <p class="font-mono text-[11px] tracking-[0.2em] uppercase text-muted mb-6">Static Analysis &middot; Effect-TS &middot; Deterministic</p>
      <h1 class="font-display text-5xl md:text-7xl lg:text-8xl leading-[0.95] tracking-tight max-w-4xl">
        Railway<br/>
        <span class="italic text-accent">Evolution</span>
      </h1>
      <p class="mt-8 text-lg md:text-xl text-muted max-w-2xl leading-relaxed">
        A money transfer workflow, built step by step. Each diagram below is the <strong class="text-ink">raw, unedited output</strong> of <span class="font-mono text-ink text-[0.9em]">effect-analyze</span> reading the TypeScript source. No code executed, no approximation.
      </p>
      <div class="mt-10 flex items-center gap-3 text-sm text-muted">
        <span class="inline-flex items-center gap-1.5 px-3 py-1 rounded-full border border-ink/10 bg-ink/[0.02]">
          <span class="w-2 h-2 rounded-full bg-ok"></span> ok path
        </span>
        <span class="inline-flex items-center gap-1.5 px-3 py-1 rounded-full border border-ink/10 bg-ink/[0.02]">
          <span class="w-2 h-2 rounded-full bg-err"></span> error branch
        </span>
        <span class="inline-flex items-center gap-1.5 px-3 py-1 rounded-full border border-ink/10 bg-ink/[0.02]">
          <span class="font-mono text-[11px]">effect-analyze</span> generated
        </span>
      </div>
    </div>
    <div class="absolute bottom-0 left-0 right-0 h-8 bg-paper" style="clip-path: polygon(0 100%, 100% 0, 100% 100%)"></div>
  </header>

  <!-- Steps -->
  <main class="max-w-6xl mx-auto px-6 py-16 md:py-24">
${results.map((r, i) => stepSection(r, i)).join("\n")}

    <!-- Closing -->
    <section class="step-card border-t border-ink/10 pt-16 md:pt-24" style="animation-delay: 0.7s">
      <div class="max-w-2xl">
        <h2 class="font-display text-4xl md:text-5xl italic text-accent mb-6">The point</h2>
        <p class="text-lg md:text-xl leading-relaxed text-muted">
          Every diagram on this page is the raw output of <span class="font-mono text-ink text-[0.9em]">effect-analyze</span> reading the TypeScript AST. No code was executed. No tests were run. No approximations were made.
        </p>
        <p class="text-lg md:text-xl leading-relaxed text-muted mt-4">
          The type system encodes which errors each step can produce. The analyzer reads that directly from the source. Same code, same diagram, every time.
        </p>
        <div class="mt-10 p-6 bg-ink text-paper rounded-lg font-mono text-sm leading-relaxed">
          <p class="text-paper/50 mb-2"># Reproduce this page</p>
          <p>cd demos/04-observability-effect</p>
          <p>npx tsx src/transfer/evolution/analyze.ts</p>
          <p>open src/transfer/evolution/index.html</p>
        </div>
        <div class="mt-10 flex flex-wrap gap-4 text-sm">
          <div class="flex items-center gap-2 px-4 py-2 border border-ink/10 rounded-lg">
            <span class="font-mono text-muted">deterministic</span>
            <span class="text-ok">&#10003;</span>
          </div>
          <div class="flex items-center gap-2 px-4 py-2 border border-ink/10 rounded-lg">
            <span class="font-mono text-muted">zero runtime</span>
            <span class="text-ok">&#10003;</span>
          </div>
          <div class="flex items-center gap-2 px-4 py-2 border border-ink/10 rounded-lg">
            <span class="font-mono text-muted">100% accurate</span>
            <span class="text-ok">&#10003;</span>
          </div>
          <div class="flex items-center gap-2 px-4 py-2 border border-ink/10 rounded-lg">
            <span class="font-mono text-muted">code reviews</span>
            <span class="text-ok">&#10003;</span>
          </div>
          <div class="flex items-center gap-2 px-4 py-2 border border-ink/10 rounded-lg">
            <span class="font-mono text-muted">onboarding</span>
            <span class="text-ok">&#10003;</span>
          </div>
          <div class="flex items-center gap-2 px-4 py-2 border border-ink/10 rounded-lg">
            <span class="font-mono text-muted">diagnostics</span>
            <span class="text-ok">&#10003;</span>
          </div>
        </div>
      </div>
    </section>
  </main>

  <footer class="border-t border-ink/10 py-8">
    <div class="max-w-6xl mx-auto px-6 flex flex-col md:flex-row items-center justify-between gap-4 text-xs font-mono text-muted">
      <p>Generated by effect-analyze &middot; Static analysis of Effect-TS programs</p>
      <p>From Magic to Science &middot; Jag Reehal</p>
    </div>
  </footer>

  <script>
    mermaid.initialize({
      startOnLoad: true,
      theme: 'base',
      themeVariables: {
        primaryColor: '#BBDEFB',
        primaryBorderColor: '#1565C0',
        primaryTextColor: '#0a0a0a',
        lineColor: '#6b6560',
        secondaryColor: '#C8E6C9',
        tertiaryColor: '#FFCDD2',
        fontFamily: '"DM Mono", monospace',
        fontSize: '13px',
      },
      flowchart: { curve: 'basis', padding: 16, htmlLabels: true, useMaxWidth: true },
    });
    window.addEventListener('scroll', () => {
      const p = Math.min(window.scrollY / (document.documentElement.scrollHeight - window.innerHeight), 1);
      document.getElementById('progress').style.transform = 'scaleX(' + p + ')';
    });
    const obs = new IntersectionObserver((entries) => {
      entries.forEach((e) => { if (e.isIntersecting) e.target.style.animationPlayState = 'running'; });
    }, { threshold: 0.1 });
    document.querySelectorAll('.step-card').forEach((c) => { c.style.animationPlayState = 'paused'; obs.observe(c); });
  <\/script>
</body>
</html>`

const htmlPath = join(scriptDir, "index.html")
writeFileSync(htmlPath, html)
console.log(`Written HTML to ${htmlPath}`)
